@startuml
actor admin
autonumber

title: US02_Sequence Diagram_Configure Access Method in System (Happy Path)

admin -> UI ++ #application : I want to configure access method
UI --> admin -- : access method name?
admin -> UI ++ #application :provides name (String)
    UI -> ":ConfigureAccessMethodController" as ConfigureAccessMethodController ++ #application : configureAccessMethod (nameString)

ConfigureAccessMethodController -> ConfigureAccessMethodController: new NameWithNumbersAndSpecialChars(nameString)

ConfigureAccessMethodController -> ":AccessMethodService" ++ #application : configureAccessMethod (nameVO)
":AccessMethodService" -> ":AccessMethodRepositorySpringDataImpl" ++ #application:  getAccessMethodByName(nameVO)
":AccessMethodRepositorySpringDataImpl" --> ":AccessMethodService" -- #application: Optional.empty()
":AccessMethodService" -> ":AccessMethodFactory" as AccessMethodFactory ++ #application: createAccessMethod(nameVO)
create "ac1:AccessMethod" as AccessMethod
AccessMethodFactory -> AccessMethod  ++ #application  : <create> (nameVO)
AccessMethodFactory --> ":AccessMethodService" -- : ac1
":AccessMethodService" -> ":AccessMethodRepositorySpringDataImpl" ++ #application: saveAccessMethod(ac1)
group save(ac1)
    ":AccessMethodRepositorySpringDataImpl" -> ":AccessMethodMapper" ++ #application: toDataModel(ac1)
    create "ac1DM: AccessMethodDataModel" as AccessMethodDataModel
    ":AccessMethodMapper" -> AccessMethodDataModel ++ #application: <create>
    ":AccessMethodMapper" --> ":AccessMethodRepositorySpringDataImpl": Optional<ac1DM>
    ":AccessMethodRepositorySpringDataImpl" -> ":AccessMethodRepositorySpringDataImpl": save(ac1DM)
    ":AccessMethodRepositorySpringDataImpl" -> ":AccessMethodMapper": toDomain(ac1DM)
    ":AccessMethodMapper" --> ":AccessMethodRepositorySpringDataImpl": Optional<ac1>
end
":AccessMethodRepositorySpringDataImpl" --> ":AccessMethodService": Optional<ac1>
":AccessMethodService" --> ConfigureAccessMethodController: Optional<ac1>
ConfigureAccessMethodController --> UI: true
UI --> admin: AC1 Created and Registered
@enduml