@startuml
!pragma layout smetana
skinparam ranksep 120
skinparam nodesep 120

class US15_UpdateTeacherWorkingPercentageController {
    +US15_UpdateTeacherWorkingPercentageController(teacherCareerProgressionRepository: ITeacherCareerProgressionRepository, teacherRepository: ITeacherRepository)
    +findAll()
    +updateWorkingPercentageInTeacherCareerProgression(date: String, workingPercentage: int, acronym: String)
}

package "Teacher Aggregate" {
    entity "<<Root>>\n <<Entity>>\n Teacher" {
    +identity()
    }
}

class "<<Value Object>>\n TeacherIDVO" {
        -ID: TeacherAcronym
    }

package "TeacherCareerProgression Aggregate" {
    entity "<<Root>>\n <<Entity>>\nTeacherCareerProgression" {
        +TeacherCareerProgression(dateVO: DateVO, workingPercentageVO: WorkingPercentageVO)
        +isLastDateEqualOrBeforeNewDate(dateVO: DateVO)
        +getTeacherCategoryID()
        +getWorkingPercentage()
        +getDate()
        +isDateAfter()
    }
}

    class "<<Value Object>>\n TeacherCareerProgressionIDVO" {
          -ID: UUIU
    }

    class "<<Value Object>>\n DateVO" {
          -date: LocalDate
    }

    class "<<Value Object>>\n WorkingPercentageVO" {
              -workingPercentage: int
   }

class TeacherCareerProgressionRepository {
    +updateWorkingPercentageInTeacherCareerProgression(dateVO: DateVO, workingPercentageVO: WorkingPercentageVO,
    teacherIDVO: TeacherIDVO)
    +findLastTCPFromTeacherID(teacherIDVO: TeacherIDVO)
}

class TeacherRepository {
    +findAll()
    +containsOfIdentity()
}

package "TeacherCategory Aggregate" {
    entity "<<Root>>\n <<Entity>>\nTeacherCategory" {
    }
}

interface ITeacherCareerProgressionRepository {
    +updateWorkingPercentageInTeacherCareerProgression(dateVO: DateVO, workingPercentageVO: WorkingPercentageVO,
    teacherIDVO: TeacherIDVO)
    +findLastTCPFromTeacherID(teacherIDVO: TeacherIDVO)
}

interface ITeacherRepository {
    +findAll()
    +containsOfIdentity()
}

class "<<Value Object>>\n TeacherCategoryIDVO" {
                -id: UUIU
}

class TeacherCareerProgressionFactoryImpl {
    +createTeacherCareerProgression(dateVO: DateVO, workingPercentageVO: WorkingPercentageVO,
                                        teacherCategoryIDVO: TeacherCategoryIDVO, teacherIDVO: TeacherIDVO)
}

interface ITeacherCareerProgressionFactory {
    +createTeacherCareerProgression(dateVO: DateVO, workingPercentageVO: WorkingPercentageVO,
                                        teacherCategoryIDVO: TeacherCategoryIDVO, teacherIDVO: TeacherIDVO)
}

class TeacherCareerProgressionListFactoryImpl {
    +createTeacherCareerProgressionList()
}

interface ITeacherCareerProgressionListFactory {
    +createTeacherCareerProgressionList()
}

class List<TeacherCareerProgression> {
}

US15_UpdateTeacherWorkingPercentageController "1" ..> "_teacherRepository \n 1" ITeacherRepository
US15_UpdateTeacherWorkingPercentageController "1" ..> "_teacherCareerProgressionRepository \n 1" ITeacherCareerProgressionRepository
"<<Root>>\n <<Entity>>\n Teacher" "_teachers         \n 1..*           " <---- "1" ITeacherRepository
"<<Value Object>>\n TeacherIDVO" "1  " <-- "\n 1..*     " "<<Root>>\n <<Entity>>\nTeacherCareerProgression"
TeacherCareerProgressionRepository "1" ..> "_teacherCareerProgressionFactory \n1" ITeacherCareerProgressionFactory
TeacherCareerProgressionFactoryImpl "1" ..> "   \n        1..*" "<<Root>>\n <<Entity>>\nTeacherCareerProgression"
ITeacherCareerProgressionRepository "1" ..> "  _teacherCareerProgressionList \n                                     1" TeacherCareerProgressionListFactoryImpl
TeacherCareerProgressionFactoryImpl ..|> ITeacherCareerProgressionFactory
TeacherCareerProgressionListFactoryImpl ..|> ITeacherCareerProgressionListFactory
ITeacherCareerProgressionListFactory ..> List
List "1" ----> "1..*" "<<Root>>\n <<Entity>>\nTeacherCareerProgression"
"<<Root>>\n <<Entity>>\n Teacher" "1" --> "1" "<<Value Object>>\n TeacherIDVO"
"<<Root>>\n <<Entity>>\nTeacherCareerProgression" "1" --> "1" "<<Value Object>>\n TeacherCareerProgressionIDVO"
"<<Root>>\n <<Entity>>\nTeacherCareerProgression" "1" --> "1" "<<Value Object>>\n DateVO"
"<<Root>>\n <<Entity>>\nTeacherCareerProgression" "1" --> "1" "<<Value Object>>\n WorkingPercentageVO"
"<<Root>>\n <<Entity>>\nTeacherCareerProgression" "1" --> "1" "<<Value Object>>\n TeacherCategoryIDVO"
"<<Value Object>>\n TeacherCategoryIDVO" "1" <-u- "1" "<<Root>>\n <<Entity>>\nTeacherCategory"
ITeacherCareerProgressionRepository <|.. TeacherCareerProgressionRepository
ITeacherRepository <|.. TeacherRepository

@enduml