@startuml
!pragma layout smetana
'left to right direction


class US17_EnrolStudentInProgrammeEditionAndSetOfCoursesEditionsController {
    +US17_EnrolStudentInProgrammeEditionAndSetOfCoursesEditionsController(programmeEditionEnrolmentRepo: ProgrammeEditionEnrolmentRepo, programmeEditionRepository: ProgrammeEditionRepository, programmeRepository ProgrammeRepository,
    courseEditionEnrolmentRepository: CourseEditionEnrolmentRepository, courseEditionRepository: CourseEditionRepository, schoolYearRepository: SchoolYearRepository, programmeEnrolmentRepository: ProgrammeEnrolmentRepository)
    +enrolStudentInProgrammeEditionAndSetOfCoursesEditionsController(student: Student, programme: Programme, schoolYear: SchoolYear)
    +getAllProgrammes(): List<Programme>
    +getAllSchoolYears(): List<SchoolYear>
}
class CourseEditionEnrolment {
    +CourseEditionEnrolment(student:Student, courseEdition: CourseEdition)
    +hasStudent (student: Student) : boolean
    +hasCourseEdition (courseEdition: CourseEdtion) : boolean
}

class CourseEditionEnrolmentRepository {
    +CourseEditionEnrolmentRepository ()
    +enrolStudentInACourseEdition (student: Student, courseEdition: CourseEdition) : boolean
    +findByStudentAndEdition (student: Student, courseEdition: CourseEdition) : Optional <CourseEditionEnrolment>
    +enrolStudentInProgrammeEditionCoursesEditions (student: Student, courseEditions: List<CourseEdition>) : void
}

class CourseEditionEnrolmentListFactory {
    +newArrayList(): List<CourseEditionEnrolment>
}

class ProgrammeEditionEnrolment {
    +ProgrammeEditionEnrolment(student:Student, programmeEdition: ProgrammeEdition)
    +getStudentUniqueNumber() : String
    +equals (obj: Object) : boolean
    +findProgrammeEditionInEnrollment () : ProgrammeEdition
}

class ProgrammeEditionEnrolmentRepo {
    +ProgrammeEditionEnrolmentRepo(programmeEditionEnrolmentFactory: ProgrammeEditionEnrolmentFactory, programmeEditionEnrolmentListFactory: ProgrammeEditionEnrolmentListFactory)
    +enrolStudentInProgrammeEdition (student: Student, programmeEdition: ProgrammeEdition) : boolean
    +isStudentEnrolledInThisProgrammeEdition(student: Student, programmeEdition: ProgrammeEdition) : boolean
}

class ProgrammeEditionEnrolmentFactory {
    +newProgrammeEditionEnrolment(student: Student, programmeEdition: ProgrammeEdition)
}

interface ProgrammeEditionEnrolmentFactoryInterface{
    +newProgrammeEditionEnrolment(student: Student, programmeEdition: ProgrammeEdition)
}

class ProgrammeEditionEnrolmentListFactory{
    +newProgrammeEditionEnrolmentList(): Set<ProgrammeEditionEnrolment>
}

interface ProgrammeEditionEnrolmentListFactoryInterface {
    +newProgrammeEditionEnrolmentList(): Set<ProgrammeEditionEnrolment>
}

class Programme {
     - name: string
     - acronym: string
     - quantityOfEcts: int
     - quantityOfSemesters: int
     + Programme (name : String, acronym : String, quantityOfEcts: int, quantityOfSemesters : int,
     degreeType : DegreeType, department : Department, programmeDirector : Teacher, programmeCourseListFactory: ProgrammeCourseListFactory)
 }

class ProgrammeRepository {
    +ProgrammeRepository(programmeFactory: ProgrammeFactory)
    +getAllProgrammes() : List<Programme>
}

class ProgrammeRepositoryListFactoryImpl {
    +copyProgrammeArrayList(List<Programme>)
}

interface ProgrammeRepositoryListFactory {
    +copyProgrammeArrayList(List<Programme>)
}

class SchoolYear {
    -_description:String
    -_startData:String
    -_endDate:String
    +SchoolYear(description: String, StartDate: String, EndDate: String)
}

class SchoolYearRepository {
    +schoolYearRepository(schoolYearFactory: SchoolYearFactory, schoolYearListFactory: SchoolYearListFactory)
    +getAllSchoolYears() : List<SchoolYear>
}

class SchoolYearListFactory {
    +copySchoolYearArrayList(List<SchoolYear>)
}

interface SchoolYearListFactoryInterface {
    +copySchoolYearArrayList(List<SchoolYear>)

}

class ProgrammeEnrolment {
    +ProgrammeEnrolment(student: Student, accessMethod: AccessMethod)
    +getStudentFromEnrolment() : Student
    +getProgrammeFromEnrolment() : Programme
}

class ProgrammeEnrolmentRepository {
    +ProgrammeEnrolmentRepository()
    +isStudentEnrolled(student: Student, programme: Programme) : boolean
}

class Student {
    -_uniqueNumber:String
    -_name:String
    -_NIF:String
    -_phone:String
    -_email:String
    _institutionalEmail:String
    +Student(uniqueNumber: String, name: String, NIF: String, phone: String, email: String, address: Address)
    +getUniqueNumber() : String
}

class Address {
     -_street:String
     -_postalCode: String
     -_location: String
     -_country: String
     +Address(street: String, postalCode: String, location: String, country: String)
}

class CourseEdition {
    +CourseEdition(programmeEdition: ProgrammeEdition, course: Course)
    +whatProgrammeEditionBelongsThisCourseEdition() : ProgrammeEdition
}

class CourseEditionRepository {
    +CourseEditionRepository(courseEditionFactory: CourseEditionFactory)
    +findCourseEditionsByProgrammeEdition(ProgrammeEdition programmeEdition) : List<CourseEdition>
}

class CourseEditionListFactory{
    +newArrayList(CourseEdition)
}

class ProgrammeEdition {
    +ProgrammeEdition(programme: Programme,schoolYear: SchoolYear)
    +findProgrammeInProgrammeEdition() : Programme
    +findSchoolYearInProgrammeEdition() : SchoolYear
}

class ProgrammeEditionRepository {
    +ProgrammeEditionRepository(programmeEditionFactory: ProgrammeEditionFactory))
    +findProgrammeEditionBySchoolYearAndProgramme(programme: Programme, schoolYear: SchoolYear) : Optional<ProgrammeEdition>
}

US17_EnrolStudentInProgrammeEditionAndSetOfCoursesEditionsController "1 " ..> "1  " ProgrammeEditionEnrolmentRepo
US17_EnrolStudentInProgrammeEditionAndSetOfCoursesEditionsController "1" ..> "1                         " ProgrammeEditionRepository
US17_EnrolStudentInProgrammeEditionAndSetOfCoursesEditionsController "1                   " ..> "1" ProgrammeRepository
US17_EnrolStudentInProgrammeEditionAndSetOfCoursesEditionsController "1 " ..> "1     " CourseEditionEnrolmentRepository
US17_EnrolStudentInProgrammeEditionAndSetOfCoursesEditionsController "1 " ..> "1  " CourseEditionRepository
US17_EnrolStudentInProgrammeEditionAndSetOfCoursesEditionsController "1" ..> "1   " SchoolYearRepository
US17_EnrolStudentInProgrammeEditionAndSetOfCoursesEditionsController "1" ..> "_programmeEnrolmentRepository 1 " ProgrammeEnrolmentRepository
Student "1        " --> "_address 1  " Address
Student "_student  1 " <-u- "* " ProgrammeEnrolment
Programme " 1 "  --> "  1 _listOfEnrollments " ProgrammeEnrolment

ProgrammeEdition "* " -->"_schoolYear 1      " SchoolYear
CourseEditionRepository "1 " -u-> "* _listCourseEditions" CourseEdition
CourseEditionRepository" 1     " -u-> "1  " CourseEditionListFactory
Student "_student 1" <-- "*" CourseEditionEnrolment
CourseEditionEnrolment "_listOfCourseEditionEnrollment *  " <-- " 1 " CourseEditionEnrolmentRepository
CourseEditionEnrolmentRepository"1" --> "1" CourseEditionEnrolmentListFactory
CourseEditionEnrolment "*" --> "1 _listOfcourseEdition              " CourseEdition

ProgrammeEdition "_programmeEdition 1                " <-- " * " ProgrammeEditionEnrolment
ProgrammeEditionEnrolment "* " --> "_student 1   " Student
ProgrammeEditionEnrolmentRepo ..> ProgrammeEditionEnrolment
ProgrammeEditionEnrolmentFactoryInterface <.. ProgrammeEditionEnrolmentRepo
ProgrammeEditionEnrolmentRepo "1"..> "1" ProgrammeEditionEnrolmentListFactory
ProgrammeEditionEnrolmentRepo ..> ProgrammeEditionEnrolmentListFactoryInterface
CourseEdition "_listOfCourseEdition *  " <-- "1   " ProgrammeEdition
ProgrammeEditionEnrolmentFactoryInterface <|.. ProgrammeEditionEnrolmentFactory
ProgrammeEditionEnrolmentListFactoryInterface <|.. ProgrammeEditionEnrolmentListFactory
ProgrammeEnrolmentRepository "1" --> "*" ProgrammeEnrolment

ProgrammeRepository ..> ProgrammeRepositoryListFactory
ProgrammeRepository ..> Programme
ProgrammeRepositoryListFactoryImpl ..|> ProgrammeRepositoryListFactory

SchoolYearRepository  ..> SchoolYearListFactoryInterface
SchoolYearListFactory ..|> SchoolYearListFactoryInterface
SchoolYearRepository  ..>  SchoolYear

@enduml

