@startuml
autonumber
skinparam sequence {
LifeLineBorderColor Grey
LifeLineBackgroundColor HoneyDew
}
title US17 - enrol a student in a programme in a given school year and in a set of courses
actor ASC
participant ":UI" as UI
ASC -> UI : I want to enrol a student in a programme in a given school year and in a set of courses.
activate UI
UI --> ASC : What student?
deactivate UI
ASC -> UI : Enter the student!

'' Get Programmes

activate UI
participant ":US17_EnrolStudentInProgrammeEditionAndSetOfCoursesEditionsController" as Controller
UI -> Controller : getAllProgrammes()
activate Controller
participant ":ProgrammeRepository" as ProgrammeRepository
Controller -> ProgrammeRepository : getAllProgrammes()
activate ProgrammeRepository
participant ":ProgrammeRepositoryListFactoryImpl" as ProgrammeRepositoryListFactoryImpl
ProgrammeRepository -> ProgrammeRepositoryListFactoryImpl : copyProgrammeArrayList(List<Programme>)
activate ProgrammeRepositoryListFactoryImpl
create "copyPgmList[i]:ProgrammeRepositoryListFactory"
ProgrammeRepositoryListFactoryImpl -> "copyPgmList[i]:ProgrammeRepositoryListFactory": copyProgrammeArrayList(List<Programme>)
activate "copyPgmList[i]:ProgrammeRepositoryListFactory"
"copyPgmList[i]:ProgrammeRepositoryListFactory" --> ProgrammeRepositoryListFactoryImpl: EmptyList<Programme>
deactivate "copyPgmList[i]:ProgrammeRepositoryListFactory"
ProgrammeRepositoryListFactoryImpl --> ProgrammeRepository : copyOfProgrammeList
deactivate ProgrammeRepositoryListFactoryImpl
ProgrammeRepository --> Controller : copyOfProgrammeList
deactivate ProgrammeRepository
Controller --> UI : listOfProgrammes
deactivate Controller
UI --> ASC : Here is the list of Programmes! What programme do you want?
deactivate UI
ASC -> UI : Enter the programme!

'' Get SchoolYears

activate UI
participant ":SchoolYearRepository" as SchoolYearRepository
UI -> Controller : getAllSchoolYears()
activate Controller
participant ":SchoolYearRepository" as SchoolYearRepository
Controller -> SchoolYearRepository : getAllSchoolYears()
activate SchoolYearRepository
participant ":SchoolYearRepositoryListFactoryImpl" as SchoolYearRepositoryListFactoryImpl
SchoolYearRepository -> SchoolYearRepositoryListFactoryImpl : copySchoolYearArrayList(List<SchoolYear>)
activate SchoolYearRepositoryListFactoryImpl
create "copySchoolYearList[i]:SchoolYearRepositoryListFactory"
SchoolYearRepositoryListFactoryImpl -> "copySchoolYearList[i]:SchoolYearRepositoryListFactory": copySchoolYearArrayList(List<SchoolYear>)
activate "copySchoolYearList[i]:SchoolYearRepositoryListFactory"
"copySchoolYearList[i]:SchoolYearRepositoryListFactory" --> SchoolYearRepositoryListFactoryImpl: EmptyList<SchoolYear>
deactivate "copySchoolYearList[i]:SchoolYearRepositoryListFactory"
SchoolYearRepositoryListFactoryImpl --> SchoolYearRepository : copyOfSchoolYearList
deactivate SchoolYearRepositoryListFactoryImpl
SchoolYearRepository --> Controller : copyOfSchoolYearsList
deactivate SchoolYearRepository
Controller --> UI : listOfSchoolYears
deactivate Controller
UI --> ASC : Here is the list SchoolYears! What schoolYear do you want?
deactivate UI
ASC -> UI : Enter the schoolYear!
activate UI
UI --> ASC : Sure?
deactivate UI
ASC -> UI : Yes!

activate UI
UI -> Controller : enrolStudentInProgrammeEditionAndSetOfCoursesEditions(student, programme, schoolYear)
activate Controller
participant ":ProgrammeEnrolmentRepository" as ProgrammeEnrolmentRepository

'' Is Student Enrolled

Controller -> ProgrammeEnrolmentRepository : isStudentEnrolled(student, programme)
activate ProgrammeEnrolmentRepository
participant "e[i]:ProgrammeEnrolment" as Enrolment
loop for each "e[i]:ProgrammeEnrolment" as Enrolment
ProgrammeEnrolmentRepository -> Enrolment : Student: getStudentFromEnrolment()
ProgrammeEnrolmentRepository -> Enrolment : Programme: getProgrammeFromEnrolment()
end
deactivate Enrolment
ProgrammeEnrolmentRepository --> Controller : True

'' Find Programme Edition by SchoolYear and Programme

deactivate ProgrammeEnrolmentRepository
participant ":ProgrammeEditionRepository" as ProgrammeEditionRepository
Controller -> ProgrammeEditionRepository : findProgrammeEditionBySchoolYearAndProgramme(programme, schoolYear)
activate ProgrammeEditionRepository
participant ":ProgrammeEdition" as ProgrammeEdition
loop for each "pe[i]:ProgrammeEditionRepository" as ProgrammeEditionRepository
ProgrammeEditionRepository -> ProgrammeEdition : programmeEdition : findProgrammeInProgrammeEdition(programme)
ProgrammeEditionRepository -> ProgrammeEdition : programmeEdition : findSchoolYearInProgrammeEdition(schoolYear)
ProgrammeEdition --> ProgrammeEditionRepository : pe1
end
ProgrammeEditionRepository --> Controller :  pe1
deactivate ProgrammeEditionRepository

'' Is Student Enrolled in This Programme Edition

participant ":ProgrammeEditionEnrolmentRepository" as ProgrammeEditionEnrolmentRepository
Controller -> ProgrammeEditionEnrolmentRepository : isStudentEnrolledInThisProgrammeEdition(student, pe1)
activate ProgrammeEditionEnrolmentRepository
participant ":ProgrammeEditionEnrolment" as ProgrammeEditionEnrolment
loop for each "pee[i]:ProgrammeEditionEnrolmentRepository" as ProgrammeEditionEnrolmentRepository
participant ":Student" as Student
ProgrammeEditionEnrolmentRepository -> ProgrammeEditionEnrolment: ProgrammeEditionEnrolment: findProgrammeEditionInEnrolment()
ProgrammeEditionEnrolmentRepository -> Student: ProgrammeEditionEnrolment: getUniqueNumber()
participant ":ProgrammeEditionEnrolment" as ProgrammeEditionEnrolment
end
ProgrammeEditionEnrolmentRepository --> Controller : False
deactivate "ProgrammeEditionEnrolmentRepository"

'' Enroll Student in Programme Edition

Controller -> ProgrammeEditionEnrolmentRepository : enrollStudentInProgrammeEdition(student, pe1)
activate "ProgrammeEditionEnrolmentRepository"
participant ":IProgrammeEditionEnrolmentFactory" as IProgrammeEditionEnrolmentFactory
ProgrammeEditionEnrolmentRepository -> IProgrammeEditionEnrolmentFactory: newProgrammeEditionEnrolment(student, pe1)
activate IProgrammeEditionEnrolmentFactory
create "pee1:ProgrammeEditionEnrolment"
IProgrammeEditionEnrolmentFactory -> "pee1:ProgrammeEditionEnrolment" : newProgrammeEditionEnrolment(student, pe1)
activate "pee1:ProgrammeEditionEnrolment"
"pee1:ProgrammeEditionEnrolment" --> IProgrammeEditionEnrolmentFactory: pee1
deactivate "pee1:ProgrammeEditionEnrolment"
IProgrammeEditionEnrolmentFactory --> ProgrammeEditionEnrolmentRepository: pee1
deactivate IProgrammeEditionEnrolmentFactory
create "pe[i]:ProgrammeEditionArrayList"
ProgrammeEditionEnrolmentRepository -> "pe[i]:ProgrammeEditionArrayList":  add(pee1)
activate "pe[i]:ProgrammeEditionArrayList"
ProgrammeEditionEnrolmentRepository <-- "pe[i]:ProgrammeEditionArrayList":  True
deactivate "pe[i]:ProgrammeEditionArrayList"
ProgrammeEditionEnrolmentRepository --> Controller : True
deactivate ProgrammeEditionEnrolmentRepository

'' Find Course Edition by Programme Edition

participant ":CourseEditionRepository" as CourseEditionRepository
Controller -> CourseEditionRepository : findCourseEditionsByProgrammeEdition(pee1)
participant ":CourseEdition" as CourseEdition
activate CourseEditionRepository
participant ":CourseEditionListFactory" as CourseEditionListFactory
CourseEditionRepository -> CourseEditionListFactory: newArrayList()
activate CourseEditionListFactory
create "ce[i]:CourseEditionArrayList"
CourseEditionListFactory -> "ce[i]:CourseEditionArrayList": newArrayList ()
activate "ce[i]:CourseEditionArrayList"
"ce[i]:CourseEditionArrayList" --> CourseEditionListFactory: EmptyList<CourseEdition>
deactivate "ce[i]:CourseEditionArrayList"
CourseEditionListFactory --> CourseEditionRepository: EmptyList<CourseEdition>
deactivate CourseEditionListFactory
loop for each "ce[i]:CourseEditionRepository" as CourseEditionRepository
CourseEditionRepository -> CourseEdition :  whatProgrammeEditionBelongsThisCourseEdition()
activate CourseEdition
CourseEdition --> CourseEditionRepository : ce1
deactivate CourseEdition
participant ":CourseEditionArrayList" as CourseEditionArrayList
CourseEditionRepository -> "ce[i]:CourseEditionArrayList" :  add(ce1)
activate "ce[i]:CourseEditionArrayList"
"ce[i]:CourseEditionArrayList" --> CourseEditionRepository: True
deactivate "ce[i]:CourseEditionArrayList"
end
participant ":CourseEditionEnrolmentRepository" as CourseEditionEnrolmentRepository
CourseEditionRepository -> CourseEditionEnrolmentRepository : ListOfCourseEditions
deactivate CourseEditionRepository
participant ":CourseEditionEnrolment" as CourseEditionEnrolment
activate CourseEditionEnrolmentRepository
loop for each "cee[i]:CourseEditionEnrolmentRepository" as CourseEditionEnrolmentRepository
CourseEditionEnrolmentRepository -> CourseEditionEnrolment : findByStudentAndEdition(student, cee[i])
CourseEditionEnrolmentRepository -> CourseEditionEnrolment : isPresent()
create CourseEditionEnrolmentHashSet
CourseEditionEnrolmentRepository -> CourseEditionEnrolmentHashSet : enrolStudentInACourseEdition(student, cee1)
activate CourseEditionEnrolmentHashSet
CourseEditionEnrolmentHashSet --> CourseEditionEnrolmentRepository : True
deactivate CourseEditionEnrolmentHashSet
end
CourseEditionEnrolmentRepository --> Controller : True
deactivate CourseEditionEnrolmentRepository
Controller --> UI : True
deactivate Controller
UI --> ASC: OK!
deactivate UI

@enduml