@startuml

title SSD: US28: Remove the enrolment of a student in a course edition

actor ASC
participant ":System" as UI

ASC -> UI : I want to remove the enrolment of a student in a course edition
UI --> ASC : What student?
ASC -> UI : Student!
UI --> ASC : What course edition?
ASC -> UI : Course edition!
UI --> ASC : Sure?
ASC -> UI : Yes
UI --> ASC : Removal successful!

@enduml
