@startuml
autonumber

title US27: As an ASC, I want to register a programme in the system, including the study plan.

actor ASC as Admin

participant ":UI" as UI #lightblue
participant ":ControllerUS27" as C #lightblue
participant ":ProgrammeRepository" as PR #lightblue

participant "ProgrammeFactory" as PF #lightblue





Admin -> UI ++ #application : I want to register a Programme in the System,\n including a Study Plan.

UI --> Admin -- : What are the attributes?

Admin -> UI ++ #application : name, acronym, quantityOfEcts, quantityOfSemesters, degreeType, \n department, programmeDirector

UI -> C ++ #application : registerAProgrammeDDDInTheSystem(name, acronym, quantityOfEcts, \nquantityOfSemesters, degreeTypeID, department, programmeDirectorID)

C -> PR ++ #application : registerProgramme(name, acronym, quantityOfEcts, quantityOfSemesters, \ndegreeTypeID, departmentID, programmeDirectorID)


PR -> PF ++ #application : registerProgramme (name, acronym, quantityOfEcts, quantityOfSemesters, \ndegreeTypeID, departmentID, programmeDirectorID)

create "P1:Programme" as P #lightblue

PF -> P ++ #application : registerProgramme (name, acronym, quantityOfEcts, quantityOfSemesters, \ndegreeTypeID, departmentID, programmeDirectorID)

P -> P : Validations


P --> PF -- : Programme P1
PF --> PR -- : Programme P1
participant ":List<Programme>" as PL
PR -> PL ++ #application : contains(P1)
PL --> PR : False
PR -> PL : add(P1)
PL --> PR --: True

PR --> C -- : True
C --> UI -- : True


UI --> Admin -- : Done! Do you also want to add a Study Plan?
Participant ":StudyPlanRepository" as SPR #lightblue

Admin -> UI ++ #application: Yes.
UI --> Admin --: Implementation Date?

Admin -> UI ++ #application: Date.


UI -> C ++ #application: createStudyPlanDDD(ProgrammeID programmeID, Date implementationDate)
C -> SPR ++ #application: createStudyPlan(ProgrammeID programmeID, Date implementationDate, DurationInYears durationInYears, quantityOfEcts)

participant ":StudyPlanFactory" as SPF #lightgreen

SPR -> SPF ++ #application: newStudyPlan(programmeID, implementationDate, durationInYears, quantityOfEcts)
create "SP1:Studyplan" as SP1 #lightblue
SPF -> SP1 ++ #application: StudyPlanDDD(programmeID, implementationDate, durationInYears, quantityOfEcts)
SP1 -> SP1 : Validations

SP1 --> SPF -- : StudyPlan SP1

SPF --> SPR -- : StudyPlan SP1
participant ":List<StudyPlan>" as SPL #lightblue
SPR -> SPL ++ #application : contains(SP1)
SPL --> SPR : False

SPR -> SPL : add(SP1)
SPL --> SPR -- : True

SPR --> C -- : True
C --> UI -- : True
UI --> Admin -- : Study Plan Created.

loop Repeat User Story 03 Add a Course \nto Programme until Study Plan is Full.
end loop

@enduml