@startuml

title US05: Register a Department in the System

autonumber
skinparam sequence {
   LifelineBorderColor black
   LifelineBackgroundColor LightBlue
 }

actor "Administrator" as Administrator #LightBlue/White
participant ":UI" as UI #LightBlue/white
participant ":US05_RegisterADepartmentInTheSystemController" as Controller #LightBlue/white
participant ":IDepartmentRepository" as DepartmentRepository #LightBlue/white
participant ":IDepartmentFactory" as DepartmentFactory #LightBlue/white
participant "d1:Department" as Department #LightBlue/white
participant "d[i]:Department" as Departmenti #LightBlue/white


Administrator -> UI: I want to register a department in the system.
activate UI
UI --> Administrator: Please provide the acronym.
Administrator -> UI: Enter acronym.
UI --> Administrator: Please provide the name.
Administrator -> UI: Enter name.
UI --> Administrator: Sure?
Administrator -> UI: Yes!

UI -> Controller: registerDepartment(acronym, name)
activate Controller

ref over Controller
    Convert acronym and name to VO
end ref

Controller -> DepartmentRepository: registerDepartment(acronymVO, nameVO)
activate DepartmentRepository
DepartmentRepository -> DepartmentFactory: createDepartment (acronymVO, nameVO)
activate DepartmentFactory
DepartmentFactory -> Department **: createDepartment (acronymVO, nameVO)


deactivate DepartmentFactory
DepartmentRepository -> Departmenti: add (d1)
activate Departmenti
Departmenti --> DepartmentRepository: True
deactivate Departmenti
DepartmentRepository --> Controller: True
deactivate DepartmentRepository

Controller --> UI: True
deactivate Controller
UI --> Administrator: Department registered
deactivate UI

@enduml