@startuml

title US05: Register a Department in the System

autonumber
skinparam sequence {
   LifelineBorderColor black
   LifelineBackgroundColor LightBlue
   skinparam shadowing true
 }

actor "Administrator" as Administrator #LightBlue/White
participant ":UI" as UI #LightBlue/white
participant ":US05_RegisterADepartmentInTheSystem\nController" as Controller #LightBlue/white
participant ":IDepartment\nService" as Service #LightBlue/white
participant "dID1: DepartmentID" as DepartmentID #LightYellow/white
participant ":IDepartment\nRepository" as DepartmentRepository #LightBlue/white
participant ":IDepartment\nFactory" as DepartmentFactory #LightBlue/white
participant "d1:Department" as Department #LightYellow/white
participant ":IDepartment\nMapper" as Mapper #LightBlue/White
participant "ddm1: DepartmentDataModel" as departmentDataModel #LightYellow/White
participant ":IDepartment\nRepositorySpringData" as departmentRepoSpringData #LightBlue/White

Administrator -> UI: I want to register a department.
activate UI
UI --> Administrator: Please provide the acronym.
Administrator -> UI: Enter acronym.
UI --> Administrator: Please provide the name.
Administrator -> UI: Enter name.
UI --> Administrator: Sure?
Administrator -> UI: Yes!

UI -> Controller: registerDepartment\n(acronym, name)
activate Controller

ref over Controller
    Convert acronym and name to VO
end ref

Controller -> Service: registerDepartment\n(acronymVO, nameVO)
activate Service

Service ->  DepartmentID**: new DepartmentID


Service -> DepartmentRepository: containsOfIdentity(dID1)
activate DepartmentRepository
DepartmentRepository -> Service: false
deactivate DepartmentRepository

Service -> DepartmentFactory: newDepartment\n(acronymVO, nameVO)
activate DepartmentFactory
DepartmentFactory -> Department **: newDepartment\n(acronymVO, nameVO)
deactivate DepartmentFactory

Service -> DepartmentRepository: register department(d1)
activate DepartmentRepository
DepartmentRepository -> Mapper: toDataModel(d1)
activate Mapper

Mapper -> departmentDataModel **: createDataModel(d1)
deactivate Mapper

DepartmentRepository -> departmentRepoSpringData: save (ddm1)
activate departmentRepoSpringData

departmentRepoSpringData -> DepartmentRepository: true
deactivate departmentRepoSpringData


DepartmentRepository -> Service: true
deactivate DepartmentRepository


Service --> Controller: True
deactivate Service

Controller --> UI: True
deactivate Controller
UI --> Administrator: Department registered
deactivate UI

@enduml