@startuml
actor Administrator as Adm
participant "US10_IWantToConfigureDegreeTypesLevelsController" as Controller #lightcoral
participant "DegreeTypeService" as S #lightgrey
participant "DegreeTypeFactoryInterface" as DTF #lightblue




Adm -> Controller : registerDegreeType(name, maxEcts)
activate Controller
Controller -> S : registerDegreeType(name, maxEcts, DegreeTypeID)
activate S
S -> DTF : registerDegreeType(name, maxEcts)
activate DTF
S -> DTF : addNewDegreeType(name, maxEcts)
create "DT1:DegreeType" as DT #yellow
DTF -> DT : Create DegreeType (name, maxEcts)
activate DT
DT --> DTF : DT1
deactivate DT
participant "DegreeTypeRepository" as DTR #lightgreen
DTF --> S : DT1
deactivate DTF
S -> DTR : add DT1 to Repository
DTR --> S : Registration Successful
deactivate DTR
S --> Controller : Registration Successful
deactivate S
Controller --> Adm : Registration Successful
deactivate Controller
@enduml
