@startuml

title US26_getNumberOfStudentsInProgrammesFromSpecifiedDepartmentInGivenSchoolYear.puml
top to bottom direction
skinparam ranksep 100
skinparam nodesep 100
skinparam classBackgroundColor #E1F5FE
skinparam linetype ortho

class US26_CountStudentsInProgrammesFromDepartmentInSchoolYearController {
    +US26_CountStudentsInProgrammesFromDepartmentInSchoolYearController( IProgrammeEditionEnrolmentRepository PEERepo,ISchoolYearRepository schoolYearRepository,IDepartmentRepository departmentRepository
    +countStudentsInProgrammeFromDepartmentInSchoolYear(departmentID: DepartmentID, schoolYearID: SchoolYearID): int
}

'Interfaces and Repositories'
interface IDepartmentRepository {
    +departmentExists(DepartmentID department) :boolean
}

class DepartmentRepositoryImpl {
    +departmentExists(DepartmentID department) :boolean
    +findDepartmentByID(DepartmentID department) :Optional <Department>
}

interface IProgrammeRepository {
    +findProgrammeByDepartment(DepartmentID department): List<ProgrammeID>
}

class ProgrammeRepositoryImpl {
     +findProgrammeByDepartment(DepartmentID department): List<ProgrammeID>
}

interface IProgrammeEditionEnrolmentRepository {
     +countStudentsInProgrammesFromDepartmentInSchoolYear(schoolYearID: SchoolYearID, List<ProgrammeID> ProgrammeIDs): int
}
class ProgrammeEditionEnrolmentRepository {
    +countStudentsInProgrammesFromDepartmentInSchoolYear(schoolYearID: SchoolYearID, List<ProgrammeID> ProgrammeIDs): int
}

interface ISchoolYearRepository {
    +schoolYearExistsByID(schoolYearID: SchoolYear): boolean
}

class SchoolYearRepository {
    +schoolYearExistsByID(schoolYearID: SchoolYear): boolean
}

'Aggregates'

package "Programme Aggregate" #LightBlue{
    class Programme <<Root>> <<Entity>> {
    +isInDepartment ( departmentID: DepartmentID): boolean
    +identity (): ProgrammeID
    }
}
class NameWithNumbersAndSpecialChars <<Value Object>> {
}
class QuantSemesters <<Value Object>> {
}
class QuantEcts <<Value Object>> {
}
class Acronym <<Value Object>> {
}
class DegreeTypeID <<Value Object>> {
}


package "Department Aggregate" #LightBlue {
    class Department <<Root>> <<Entity>> {
     +getDepartmentID(): DepartmentID
    }
}
class Name <<Value Object>> {
}

class ProgrammeID <<Value Object>> {
     +equals ()
}
class DepartmentID <<Value Object>> {
     +equals ()
}
class SchoolYearID <<Value Object>> {
     +equals ()
}
class ProgrammeEditionID <<Value Object>> {
     +isSameProgrammeEdition ()
}
class TeacherID <<Value Object>> {
}

package "ProgrammeEditionEnrolment Aggregate" #LightBlue {
    class ProgrammeEditionEnrolment <<Root>> <<Entity>> {
      +isEnrolmentAssociatedToProgrammeAndSchoolYear(schoolYearID: SchoolYearID, programmeIDs: List<ProgrammeID>): boolean
      +findStudentInProgrammeEdition(): StudentID
    }
}
class ProgrammeEditionEnrolmentID <<Value Object>> {
}
class ProgrammeEditionID <<Value Object>> {
}
class StudentID <<Value Object>> {
}
class LocalDate <<Value Object>> {
}

 package "SchoolYear Aggregate" #Lightblue{
     class SchoolYear <<Root>> <<Entity>>  {
        +identity(): SchoolYearID
    }
 }
 class Date <<Value Object>> {
 }
 class Description <<Value Object>> {
 }


 SchoolYear "1" --> "1" Description
 SchoolYear "1" --> "1 _startDate\n" Date
 SchoolYear "1" --> "1 _endDate" Date

 ProgrammeEditionEnrolment "1" --> "1" ProgrammeEditionEnrolmentID
 ProgrammeEditionEnrolment "1" --> "1" ProgrammeEditionID
 ProgrammeEditionEnrolment "1" --> "1" StudentID
 ProgrammeEditionEnrolment "1" --> "1" LocalDate

Programme "1" --> "1" NameWithNumbersAndSpecialChars
Programme "1" --> "1" QuantSemesters
Programme "1" --> "1" QuantEcts
Programme "1" --> "1" Acronym
Programme "1" --> "1" DegreeTypeID
Programme "1" --> "1 _programmeDirectorID" TeacherID

Department "1" --> "1" Name
Department "1" --> "1 _director" TeacherID

ProgrammeEditionEnrolmentRepository "1" --> "1..*" ProgrammeEditionEnrolment
ProgrammeEditionEnrolment "1" --> "1" ProgrammeEditionID
ProgrammeEditionID "1" --> "1" ProgrammeID
ProgrammeEditionID "1" --> "1" SchoolYearID
SchoolYearRepository "1" --> "1..*" SchoolYear
SchoolYear "1" --> "1 _schoolYearID" SchoolYearID
Department "1" --> "1 _departmentID" DepartmentID
DepartmentRepositoryImpl "1" --> "1..*" Department
ProgrammeRepositoryImpl "1" --> "1..*" Programme
Programme "1" --> "1 _departmentID" DepartmentID
Programme "1" -u-> "1 _programmeID" ProgrammeID
US26_CountStudentsInProgrammesFromDepartmentInSchoolYearController "1" ..> "1 _departmentRepository" "IDepartmentRepository"
US26_CountStudentsInProgrammesFromDepartmentInSchoolYearController "1" ..> "1 _peeRepo" "IProgrammeEditionEnrolmentRepository"
US26_CountStudentsInProgrammesFromDepartmentInSchoolYearController "1" ..> "1 _pRepo" "IProgrammeRepository"
US26_CountStudentsInProgrammesFromDepartmentInSchoolYearController "1" ..> "1 _schoolYearRepository"  "ISchoolYearRepository"
IDepartmentRepository <|.. DepartmentRepositoryImpl
IProgrammeRepository <|.. ProgrammeRepositoryImpl
IProgrammeEditionEnrolmentRepository <|.. ProgrammeEditionEnrolmentRepository
ISchoolYearRepository <|.. SchoolYearRepository

@enduml
