@startuml

title US26_getNumberOfStudentsInProgrammesFromSpecifiedDepartmentInGivenSchoolYear.puml
/'left to right direction'/

class US26_CountStudentsInProgrammesFromDepartmentInSchoolYearController {
    +US26_CountStudentsInProgrammesFromDepartmentInSchoolYearController( ProgrammeEditionEnrolmentRepo PEERepo,SchoolYearRepository schoolYearRepository,DepartmentRepository departmentRepository)
    +countStudentsInProgrammeFromDepartmentInSchoolYear(department: Department, schoolYear: SchoolYear): int
}

class Department {
    -_name: String
    -_acronym: String
    +Department(acronym: String, name: String)
    +equals(obj: Object): boolean
}

class DepartmentRepository {
    +DepartmentRepository(departmentFactory: DepartmentFactory)
    +departmentExists(department: Department): boolean
}

class ProgrammeEditionEnrolmentRepo {
    +ProgrammeEditionEnrolmentRepo(programmeEditionEnrolmentFactory: ProgrammeEditionEnrolmentFactory)
    +countStudentsInProgrammesFromDepartmentInSchoolYear(department: Department, schoolYear: SchoolYear): int
}

class ProgrammeEditionEnrolment {
    -_enrolmentDate: LocalDate
    +ProgrammeEditionEnrolment(student: Student, programmeEdition: ProgrammeEdition, _enrolmentDate: LocalDate)
    +isEnrolmentAssociatedToDepartmentAndSchoolYear(department: Department, schoolYear: SchoolYear): boolean
    +getStudentUniqueNumber(): int
}

class SchoolYearRepository {
    +SchoolYearRepository(schoolYearFactory: SchoolYearFactory)
    +schoolYearExists(schoolYear: SchoolYear): boolean
}

class SchoolYear {
    -_description: String
    -_startDate: LocalDate
    -_endDate: LocalDate
    +SchoolYear(description: String, startDate: String, endDate: String)
    +isSameSchoolYear(newSchoolYear: SchoolYear): boolean
}

class ProgrammeEdition {
    +ProgrammeEdition(programme: Programme, schoolYear: SchoolYear)
    +isEditionAssociatedToDepartmentAndSchoolYear(department: Department, schoolYear: SchoolYear): boolean
}

class Programme {
    -_name: String
    -_acronym: String
    -_quantityOfEcts: int
    -_quantityOfSemesters: int
    +Programme(name: String, acronym: String, quantityOfEcts: int, quantityOfSemesters: int, degreeType: DegreeType, department: Department, programmeDirector: Teacher)
    +isInDepartment (department: Department): boolean
}

Class Student {
    -_uniqueNumber: String
    -_name: String
    -_NIF: String
    -_phone: String
    -_email: String
    -_institutionalEmail: String
    +Student(uniqueNumber: String, name: String, NIF: String,phone: String, email: String, address: Address)
    +getUniqueNumber(): String
}

Department "*\n _departmentsList" <-- "1" DepartmentRepository
US26_CountStudentsInProgrammesFromDepartmentInSchoolYearController "1" ..> "1\n_departmentRepository" DepartmentRepository
US26_CountStudentsInProgrammesFromDepartmentInSchoolYearController "1" ..> "_schoolYearRepository 1" SchoolYearRepository
US26_CountStudentsInProgrammesFromDepartmentInSchoolYearController "1" ..> "1\n_peeRepo" ProgrammeEditionEnrolmentRepo
ProgrammeEditionEnrolmentRepo "1" --> "_programmeEditionEnrolmentList  * " ProgrammeEditionEnrolment
SchoolYearRepository "1" --> "_schoolYearList\n*" SchoolYear
ProgrammeEdition "*\n_programme" --> "1" Programme
ProgrammeEdition "1" --> "_schoolYear 1" SchoolYear
Programme"*"-->"1 _department" Department
ProgrammeEdition"1\n_programmeEdition"<--"*" ProgrammeEditionEnrolment
ProgrammeEditionEnrolment"*"-->"1 _student" Student
@enduml
