@startuml
autonumber
skinparam sequenceMessageAlign center
title US08: I want to register a Student in the system

actor ASC
participant ":UI" as UI #implementation
participant "ctrl1:RegisterStudentInSystemController" as ctrl #lightyellow
participant "sService1:StudentService" as service #lightblue
participant "sf1:StudentFactory" as SF #technology
participant "address1:Address" as A #physical
participant "s1:Student" as s1 #strategy
participant "sr1:StudentRepository" as SR #lightcyan
participant "s[i]:Student" as Student #strategy

activate ASC
ASC -> UI: I want to register a student in the system
activate UI
UI --> ASC: What is the Student's information?
deactivate UI
ASC -> UI: uniqueNumber, name, NIF, phone, email, \n street, postalCode, location, country
activate UI
UI -> ctrl: I want to register a Student in the system \n (uniqueNumber, name, NIF, phone, email, \n street, postalCode, location, country)
activate ctrl

ref over ctrl
    create studentID, name, NIF, phone, email,
    street, postalCode, location, country and academicEmail VOs
end ref

ctrl -> service: registerStudent (studentIDVO, nameVO, NIFVO, phoneVO, \n emailVO, streetVO, postalCodeVO, locationVO, \n countryVO, academicEmailVO)
activate service

service -> SF: newStudent (studentIDVO, nameVO, NIFVO, phoneVO, \n emailVO, streetVO, postalCodeVO, locationVO, \n countryVO, academicEmailVO)
activate SF

SF -> A**: new Address \n (streetVO, postalCodeVO, locationVO, countryVO)
activate A
A --> SF: address1
deactivate A

SF -> s1**: new Student \n (studentIDVO, nameVO, NIFVO, phoneVO, \n emailVO, address1, academicEmailVO)
activate s1
s1 --> SF: s1
deactivate s1
SF -> SR: existsByStudentIDOrNIF(s1)
activate SR
loop for each Student in SR
    SR -> Student: isEquals(s1) || sameAs(s1)
    activate Student
end

Student --> SR : False
deactivate Student
SR --> SF: False
deactivate SR
SF --> service: s1
deactivate SF
service -> SR: save(s1)
activate SR
SR -> SR: add(s1)
SR --> service: s1
deactivate SR
service --> ctrl : s1
deactivate service
ctrl --> UI: s1
deactivate ctrl
UI --> ASC: Success!
deactivate UI

@enduml