@startuml
autonumber
skinparam sequenceMessageAlign center
skinparam sequenceLifeLineBackgroundColor lightblue
title Diagram Referenced in US15_SequenceDiagram

participant ":TeacherCareerProgressionRepoImpl" as TCPRepo #lightblue
participant ":TeacherCareerProgressionMapperImpl" as TCPMapper #lightblue
participant "tcp1:TeacherCareerProgression" as TCP #lightblue
participant "dateVO:Date" as DateVO #lightblue
participant "workingPercentageVO:WorkingPercentage" as WPVO #lightblue
participant "teacherCategoryVO:TeacherCategory" as TCVO #lightblue
participant "TeacherIDVO:TeacherID" as TID #lightblue
participant ":TeacherCareerProgressionDataModel" as TCPDM #lightblue


TCPRepo -> TCPMapper : toDataModel

activate TCPMapper
TCPMapper -> TCP : getDate(date)
activate TCP
TCP --> TCPMapper : date
deactivate TCP
TCPMapper -> DateVO : getLocalDate(date)
activate DateVO
DateVO -->TCPMapper : dateVO
deactivate DateVO

TCPMapper -> TCP : getWorkingPercentage(workingPercentage)
activate TCP
TCP --> TCPMapper : workingPercentage
deactivate TCP
TCPMapper -> WPVO : getWorkingPercentage(workingPercentage)
activate WPVO
WPVO -->TCPMapper : workingPercentageVO
deactivate WPVO

TCPMapper -> TCP : getTeacherCategory(teacherCategory)
activate TCP
TCP --> TCPMapper : teacherCategory
deactivate TCP
TCPMapper -> TCVO : getTeacherCategory(teacherCategory)
activate TCVO
TCVO -->TCPMapper : teacherCategoryVO
deactivate TCVO

TCPMapper -> TCP : getTeacherID(teacherID)
activate TCP
TCP --> TCPMapper : teacherID
deactivate TCP
TCPMapper -> TID : getTeacherID(teacherID)
activate TID
TID -->TCPMapper : teacherIDVO
deactivate TID


TCPMapper -> TCPDM : create TeacherCareerProgressionDataModel(dateVO, workingPercentageVO, \n teacherCategoryVO, teacherIDVO)
activate TCPDM
TCPDM --> TCPMapper : tcpDataModel
TCPMapper --> TCPRepo : tcpDataModel
deactivate TCPMapper

@enduml