@startuml
autonumber
skinparam sequenceMessageAlign center
skinparam sequenceLifeLineBackgroundColor lightblue
title Diagram Referenced in US15_SequenceDiagram

participant ":TeacherCareerProgressionRepoImpl" as TCPRepo #lightblue
participant ":TeacherIDMapperImpl" as TMapper #lightblue
participant ":TeacherID" as TID #lightblue
participant ":TeacherAcronym" as TAVO #lightblue
participant ":TeacherDataModel" as TDM #lightblue

TCPRepo -> TMapper : toDataModel(teacherID)
activate TCPRepo
TMapper -> TID : getTeacherAcronym()
activate TID
TID --> TMapper : teacherAcronym
deactivate TID
TMapper -> TAVO : getAcronym()
activate TAVO
TAVO --> TMapper :acronym
deactivate TAVO
TMapper ->TDM : createDataModel (teacherID)
activate TDM


TDM --> TMapper : teacherIDDataModel
deactivate TDM
TMapper --> TCPRepo :teacherIDDataModel
deactivate TCPRepo
@enduml
