@startuml DomainModel_US21_Full_Cleaned

title Domain Model - US21: Get the Number of Students Enrolled in a Programme Edition


  ' === CONTROLLER ===
  class US21_IWantToGetTheNumberOfStudentsEnrolledInAProgrammeEditionController {
      - _programmeEditionEnrollmentService: IProgrammeEditionEnrolmentService
      + US21_IWantToGetTheNumberOfStudentsEnrolledInAProgrammeEditionController(programmeEditionEnrollmentService: IProgrammeEditionEnrolmentService)
      + iWantToGetTheNumberOfStudentsEnrolledInAProgrammeEdition(programmeEdition: ProgrammeEditionID): int
      + getAllProgrammeEditions(): List<ProgrammeEdition>
  }

  ' === VALUE OBJECTS ===


  ' === AGGREGATE ===
  package "ProgrammeEditionEnrolment Aggregate" #LightBlue {
    class ProgrammeEditionEnrolment <<Root>> <<Entity>> {
        + ProgrammeEditionEnrolment(studentId: StudentID, programmeEditionId: ProgrammeEditionID)
        + getStudentUniqueNumber(): String
        + equals(obj: Object): boolean
        + findProgrammeEditionInEnrollment(): ProgrammeEditionID
    }

    class ProgrammeEditionID <<Value Object>> {
          - _id: long
          + ProgrammeEditionID(id: long)
          + getId(): long
          + equals(object: Object): boolean
          + hashcode(): int
          + toString(): String
      }

      class StudentID <<Value Object>> {
          - _uniqueNumber: int
          + StudentID(uniqueNumber: int)
          + isUniqueNumberValid(): boolean
      }

      class ProgrammeEditionEnrolmentID <<Value Object>> {
          - _id: long
          + ProgrammeEditionEnrolmentID(id: long)
          + getId(): long
          + equals(object: Object): boolean
          + hashcode(): int
          + toString(): String
      }
  }

interface IProgrammeEditionEnrolmentFactory {
 + newProgrammeEditionEnrolment(StudentID studentId, ProgrammeEditionID programmeEditionId)
}

class ProgrammeEditionEnrolmentFactoryImpl {
 + newProgrammeEditionEnrolment(StudentID studentId, ProgrammeEditionID programmeEditionId)
}


interface IProgrammeEditionEnrolmentRepository {
    + getAllProgrammeEditionsEnrolmentByProgrammeEditionID: List<ProgrammeEditionEnrolment>
  }

interface IProgrammeEditionEnrolmentService {
    + totalStudentsInProgrammeEdition(programmeEditionID: ProgrammeEditionID): int
}

class ProgrammeEditionEnrolmentServiceImpl {
    + totalStudentsInProgrammeEdition(programmeEditionID: ProgrammeEditionID): int
}

class ProgrammeEditionEnrolmentRepositoryImpl {
    + getAllProgrammeEditionsEnrolmentByProgrammeEditionID: List<ProgrammeEditionEnrolment>
}

interface IProgrammeEditionEnrolmentSpringData {
   + findAllProgrammeEditionsEnrolmentByProgrammeEdition(programmeEditionID: ProgrammeEditionID): List<Student>
}

interface IProgrammeEditionEnrolmentMapper {
    + toDomain(programmeEditionEnrollment: ProgrammeEditionEnrollment)
    + toDataModel(programmeEditionEnrollmentDataModel: ProgrammeEditionEnrollmentDataModel)
}

class ProgrammeEditionEnrolmentMapper {
    + toDomain(programmeEditionEnrollment: ProgrammeEditionEnrollment)
    + toDataModel(programmeEditionEnrollmentDataModel: ProgrammeEditionEnrollmentDataModel)
}

interface JpaRepository {
}
  ' === RELATIONSHIPS ===
  ProgrammeEditionEnrolment --> ProgrammeEditionID: contains
  ProgrammeEditionEnrolment --> StudentID: contains
  ProgrammeEditionEnrolment --> ProgrammeEditionEnrolmentID: contains

  US21_IWantToGetTheNumberOfStudentsEnrolledInAProgrammeEditionController -down-> IProgrammeEditionEnrolmentService: uses

  IProgrammeEditionEnrolmentRepository <|..right- ProgrammeEditionEnrolmentRepositoryImpl: implements
  ProgrammeEditionEnrolmentServiceImpl -left..|> IProgrammeEditionEnrolmentService: implements
  IProgrammeEditionEnrolmentService -down-> IProgrammeEditionEnrolmentRepository: uses
  IProgrammeEditionEnrolmentRepository --> ProgrammeEditionEnrolment: uses
  ProgrammeEditionEnrolmentRepositoryImpl --> IProgrammeEditionEnrolmentSpringData: uses
  IProgrammeEditionEnrolmentSpringData --|> JpaRepository: extends

  ProgrammeEditionEnrolmentMapper -right..|> IProgrammeEditionEnrolmentMapper: implements
  IProgrammeEditionEnrolmentRepository -left-> IProgrammeEditionEnrolmentMapper: uses

  ProgrammeEditionEnrolmentFactoryImpl -left..|> IProgrammeEditionEnrolmentFactory: implements
  IProgrammeEditionEnrolmentMapper -down-> IProgrammeEditionEnrolmentFactory: uses
}

@enduml
