@startuml
title: US21_GET_THE_NUMBER_OF_STUDENTS_ENROLLED_IN_A_PROGRAMME_EDITION_(DDD SEQUENCE SYSTEM DIAGRAM)
autonumber

actor ASC
participant SYSTEM

ASC -> SYSTEM:  I want to get the number of students enrolled in a programme edition!
SYSTEM --> ASC -- : Which Degree Type?
ASC -> SYSTEM: This Degree Type!
SYSTEM --> ASC -- : Which Programme?
ASC -> SYSTEM: This Programme!
SYSTEM --> ASC -- : Which Programme Edition?
ASC -> SYSTEM: This Programme Edition!
SYSTEM --> ASC -- : This is the number of Students in the Programme Edition, int.

@enduml