@startuml
title: US19_CREATE A COURSE EDITION_SEQUENCE SYSTEM DIAGRAM
autonumber

actor ASC
participant SYSTEM
ASC -> SYSTEM:  I want to create a Course Edition
SYSTEM --> ASC -- : which degree type??
ASC -> SYSTEM:  degree type!
SYSTEM --> ASC -- : which programme??
ASC -> SYSTEM: programme!
SYSTEM --> ASC -- : which programme edition??
ASC -> SYSTEM: programme edition!
SYSTEM --> ASC -- : which course from the study plan?
ASC -> SYSTEM: course in study plan!
SYSTEM --> ASC --: Success


@enduml