@startuml
title: US19_CREATE COURSE EDITION_SEQUENCE DIAGRAM
autonumber

actor ASC
participant ":UI" as UI
participant ":CreateCourseEditionController" as CT
participant ":DegreeTypeRepository" as DTR
participant ":ProgrammeRepository" as PR
participant ":StudyPlanRepository" as SPR
participant ":CourseInStudyPlanRepository" as CSPR
participant ":ProgrammeEditionRepository" as PER
participant ":CourseEditionRepository" as CER
participant ":CourseEditionFactory" as CEF


ASC -> UI ++ #application :  I want to create a Course Edition
UI -> CT ++ #application: getAllDegreeTypes()
CT -> DTR ++ #application: getAllDegreeTypes()
DTR --> CT -- : dTL1
ref over CT
    Convert DregreeTypeList to DegreeTypeDTOList
end ref
CT --> UI -- : dTL1_DTO
UI --> ASC -- : which degree type??

ASC -> UI ++ #application :  degree Type 1!
UI -> CT ++ #application: getProgrammesByDegreeTypeID(dT1_DTO)
ref over CT
    Convert DegreeTypeDTO to DegreeTypeID
end ref
CT -> PR ++ #application: getProgrammesByDegreeTypeID(dT1ID)
PR --> CT -- : pL1
ref over CT
    Convert ProgrammeList to ProgrammeDTOList
end ref
CT --> UI -- : pL1_DTO
UI --> ASC -- : which programme??

ASC -> UI ++ #application : programme 1!
UI -> CT ++ #application: getCoursesInStudyPlanByProgrammeID(p1_DTO)
ref over CT
    Convert ProgrammeDTO to ProgrammeID
end ref
CT -> SPR ++ #application: getLatestStudyPlanIDByProgrammeID(p1_ID)
SPR --> CT -- : sP1_ID
CT -> CSPR ++ #application: getCoursesInStudyPlanByStudyPlanID(sP1_ID)
CSPR --> CT -- : cSPL1
ref over CT
    Convert CourseInStudyPlanList to CourseInStudyPlanDTOList
end ref
CT --> UI -- : cSPL1_DTO
UI --> ASC -- : which course from the study plan??

ASC -> UI ++ #application : course in study plan 1!
UI -> CT ++ #application: getAllProgrammeEditions(p1_ID)
CT -> PER ++ #application: getAllProgrammeEditions(p1_ID)
PER --> CT -- : pEL1
ref over CT
    Convert ProgrammeEditionList to ProgrammeEditionDTOList
end ref
CT --> UI -- : pEL1_DTO
UI --> ASC -- : which programmeEdition??


ASC -> UI ++ #application : programme edition 1!
UI -> CT ++ #application : createCourseEdition(cSP1_DTO,pE1_DTO)
ref over CT
    Convert ProgrammeEditionDTO to ProgrammeEditionID
    Convert CourseInStudyPlanDTO to CourseInStudyPlanID
end ref
CT -> CER ++ #application : createAndSaveCourseEdition(cSpID1,pEID1)
CER -> CEF ++ #application : createCourseEdition(cSpID1,pEID1)

create "cEID1:CourseEditionID" as CEID #lightblue
CEF --> CEID : <create> (pEID1,cSpID1)
create "cE1:CourseEdition" as CE #lightblue
CEF --> CE : <create> (cEID1,cEcSpID1,pEID1)
CEF --> CER -- : cE1
CER -> CER : isCourseEditionAlreadyInRepository (cE1)
CER -> CER : addCourseEdition (cE1)

CER --> CT --: true
CT --> UI --: true
UI --> ASC --: true

participant "dTL1\n:List<DegreeType>" as DTL
participant "dTL1_DTO\n:List<DegreeTypeDTO>" as DTL_DTO
participant "dT1_DTO\n:DegreeTypeDTO" as DT_DTO
participant "dT1ID\n:DegreeTypeID" as DT_ID
participant "pL1\n:List<Programme>" as PL
participant "pL1_DTO\n:List<ProgrammeDTO>" as PL_DTO
participant "p1_DTO\n:Programme" as PG_DTO
participant "p1ID\n:ProgrammeID" as PG_ID
participant "cSPL1\n:List<CourseInStudyPlan>" as CSPL
participant "cSPL1_DTO\n:List<CourseInStudyPlanDTO>" as CSPL_DTO
participant "cSP1_DTO\n:CourseInStudyPlanDTO" as CSP_DTO
participant "cSP1_ID\n:CourseInStudyPlanID" as CSP_ID
participant "pEL1\n:List<ProgrammeEdition>" as PEL
participant "pEL1_DTO\n:List<ProgrammeEditionDTO>" as PEL_DTO
participant "pE1_DTO\n:ProgrammeEditionDTO" as PE_DTO
participant "pE1_ID\n:ProgrammeEditionID" as PE_ID

@enduml