@startuml
skinparam sequenceMessageAlign center
skinparam sequenceLifeLineBackgroundColor lightblue
autonumber
actor ASC
participant ":UI" as UI
participant "ctrl1 : EnrolAStudentInProgrammeController" as CTRL #lightgreen
participant "peService : ProgrammeEnrolmentService" as PEService #silver
participant "pef : ProgrammeEnrolmentFactoryImpl" as PEFactory
participant "ProgrammeEnrolmentRepo" as ProgrammeEnrolmentRepo #lightblue
participant "<<Interface>>IProgrammeEnrolmentRepositorySpringData" as IPERepoSpringData #lightyellow
participant "ProgrammeEnrolmentMapper" as PEMapper
participant "peIDDataModel : PEIDMapper" as PEIDMapper
participant "programmeIDDataModel : ProgrammeIDMapper" as ProgrammeIDMapper
participant "studentIDDataModel : StudentIDDataModel" as StudentIDMapper
participant "amIDDataModel : AMIDMapper" as AMIDMapper
participant "peDomain : ProgrammeEnrolment" as ProgrammeEnrolment
participant Date
participant "peDataModel : ProgrammeEnrolmentDataModel" as PEDataModel


ASC -> UI : I want to enrol a student in a programme.
activate UI
UI --> ASC : Student?
deactivate UI
ASC -> UI : uniqueNumber
activate UI
UI --> ASC : AccessMethod?
deactivate UI
ASC -> UI : accessMethodName
activate UI
UI --> ASC : Programme?
deactivate UI
ASC -> UI : programmeAcronym
activate UI
UI --> ASC : Date?
deactivate UI
ASC -> UI : enrolmentDate
activate UI
UI -> CTRL : enrolStudentInProgramme \n (studentIDDTO, accessMethodIDDTO,\n programmeIDDTO, dateDTO)
activate CTRL
CTRL -> PEService : enrolStudentInProgramme \n (studentIDDTO, accessMethodIDDTO,\n programmeIDDTO, dateDTO)
activate PEService
|||
ref over PEService
    \t \t \t \t \t Convert DTO to VO \t
end ref
|||

PEService -> PEFactory: createProgrammeEnrolment\n(studentIDVO, amIDVO, pIDVO, enrolmentDateVO)
activate PEFactory
PEFactory -> ProgrammeEnrolment**: createProgrammeEnrolment\n(studentIDVO, amIDVO, pIDVO, enrolmentDateVO)

activate ProgrammeEnrolment
ProgrammeEnrolment -> ProgrammeEnrolment : validateAndFormatDate(date)
ProgrammeEnrolment --> PEFactory: peDomain
deactivate ProgrammeEnrolment

PEFactory -> ProgrammeEnrolment : getProgrammeEnrolmentID(programmeEnrolment)
activate ProgrammeEnrolment
ProgrammeEnrolment --> PEFactory : peIDDomain
deactivate ProgrammeEnrolment
PEFactory -> IPERepoSpringData : existsByID(peIDDomain)
activate IPERepoSpringData
IPERepoSpringData ->
IPERepoSpringData <--
PEFactory <-- IPERepoSpringData : false
deactivate IPERepoSpringData
PEFactory --> PEService: peDomain
deactivate PEFactory

PEService -> ProgrammeEnrolmentRepo : save(peDomain)
activate ProgrammeEnrolmentRepo




ProgrammeEnrolmentRepo -> PEMapper : toDataModel(peDomain)
activate PEMapper
PEMapper -> PEIDMapper : toDataModel(peIDDomain)
activate PEIDMapper
PEIDMapper -> ProgrammeEnrolment : getProgrammeEnrolmentID(peDomain)
activate ProgrammeEnrolment
ProgrammeEnrolment --> PEIDMapper : peIDDomain
deactivate ProgrammeEnrolment
PEIDMapper --> PEMapper : peIDDataModel
deactivate PEIDMapper

PEMapper -> ProgrammeIDMapper : toData(programmeIDDomain)
activate ProgrammeIDMapper
ProgrammeIDMapper -> ProgrammeEnrolment : getProgrammeID(peDomain)
activate ProgrammeEnrolment
ProgrammeEnrolment --> ProgrammeIDMapper : programmeIDDomain
deactivate ProgrammeEnrolment
ProgrammeIDMapper --> PEMapper : programmeIDDataModel
deactivate ProgrammeIDMapper

PEMapper -> StudentIDMapper : domainToDataModel(studentIDDomain)
activate StudentIDMapper
StudentIDMapper -> ProgrammeEnrolment : getStudentID(peDomain)
activate ProgrammeEnrolment
ProgrammeEnrolment --> StudentIDMapper : studentIDDomain
deactivate ProgrammeEnrolment
StudentIDMapper --> PEMapper : studentIDDataModel
deactivate StudentIDMapper

PEMapper -> AMIDMapper : toDataModel(amIDDomain)
activate AMIDMapper
AMIDMapper -> ProgrammeEnrolment : getAccessMethodID(peDomain)
activate ProgrammeEnrolment
ProgrammeEnrolment --> AMIDMapper : amIDDomain
deactivate ProgrammeEnrolment
AMIDMapper --> PEMapper : amIDDataModel
deactivate AMIDMapper

PEMapper -> ProgrammeEnrolment : getDate(peDomain)
activate ProgrammeEnrolment
ProgrammeEnrolment -> Date : getLocalDate(Date)
activate Date
Date --> ProgrammeEnrolment : localDate
deactivate Date
ProgrammeEnrolment --> PEMapper : localDate
deactivate ProgrammeEnrolment

PEMapper -> PEDataModel : createPEDataModel(peIDDataModel, programmeIDDataModel, studentIDDataModel, amIDDataModel, localDate)
activate PEDataModel
PEDataModel --> PEMapper : peDataModel
deactivate PEDataModel
PEMapper -> ProgrammeEnrolmentRepo : peDataModel
deactivate PEMapper

ProgrammeEnrolmentRepo -> IPERepoSpringData : save(peDataModel)
activate IPERepoSpringData
IPERepoSpringData ->
IPERepoSpringData <--
IPERepoSpringData --> ProgrammeEnrolmentRepo : peDataModel
deactivate IPERepoSpringData


ProgrammeEnrolmentRepo --> PEService: true
deactivate ProgrammeEnrolmentRepo

PEService -> CTRL : true

CTRL --> UI : true
deactivate CTRL
UI --> ASC : Success
deactivate UI
Deactivate IPERepoSpringData

@enduml