@startuml
skinparam {
  ActivityPadding 2
  ActivityMargin 2
  BoxPadding 2
}
skinparam defaultTextAlignment center

autonumber

participant ":IProgrammeEditionEnrolmentRepository" as ProgrammeEditionEnrolmentRepository
activate ProgrammeEditionEnrolmentRepository #E1F5FE
create ":ArrayList"
ProgrammeEditionEnrolmentRepository -> ":ArrayList": create ()
loop for each "pee[i]:ProgrammeEditionEnrolment" in ProgrammeEditionEnrolmentRepository
participant ":ProgrammeEditionEnrolment" as ProgrammeEditionEnrolment
ProgrammeEditionEnrolmentRepository -> ProgrammeEditionEnrolment : findStudentInProgrammeEdition (studentID)
activate ProgrammeEditionEnrolment #E1F5FE
ProgrammeEditionEnrolment --> ProgrammeEditionEnrolmentRepository : pee1
deactivate ProgrammeEditionEnrolment
ProgrammeEditionEnrolmentRepository -> ProgrammeEditionEnrolment :  findProgrammeEditionInEnrolment()
activate ProgrammeEditionEnrolment #E1F5FE
ProgrammeEditionEnrolment --> ProgrammeEditionEnrolmentRepository : pe1ID
deactivate ProgrammeEditionEnrolment
ProgrammeEditionEnrolmentRepository -> ":ArrayList":  add (pe1ID)
activate ":ArrayList" #E1F5FE
":ArrayList" --> ProgrammeEditionEnrolmentRepository: True
deactivate ":ArrayList"
end
@enduml