@startuml
autonumber

title US06: UpdateDepartmentDirectorOfADepartment
actor Administrator
participant ":UI" as UI

Administrator -> UI: I want to update the Department Director of a Department!
activate UI #ddfada
participant ":US06_IWantToUpdateTheDepartmentDirectorOfADepartmentController" as Controller
UI -> Controller: getAllDepartments ()
activate Controller #ddfada
participant ":DepartmentRepository" as DepartmentRepository
Controller -> DepartmentRepository: getDepartments ()
activate DepartmentRepository #ddfada
DepartmentRepository --> Controller: setOfDepartments
deactivate DepartmentRepository
Controller --> UI: setOfDepartments
deactivate Controller

UI --> Administrator: What Department?
deactivate UI
Administrator -> UI: Enter the Department!
activate UI #ddfada
UI --> Administrator: What Teacher?
deactivate UI
Administrator -> UI: Enter the Teacher!
activate UI #ddfada
UI --> Administrator: Sure?
deactivate UI
Administrator -> UI: Yes!
activate UI #ddfada

UI -> Controller : updateDepartmentDirector (department, teacher)
activate Controller #ddfada
participant ":DepartmentRepository" as DepartmentRepository
Controller -> DepartmentRepository: updateOfDepartmentDirector(department, teacher)
participant ":Department" as Department
activate DepartmentRepository #ddfada
DepartmentRepository -> Department: changeDirector (Teacher)
activate Department #ddfada
participant ":Teacher" as Teacher
Department -> Teacher: isInDepartment (d1)
activate Teacher #ddfada
Teacher --> Department: True
deactivate Teacher
Department --> DepartmentRepository: True
deactivate Department
DepartmentRepository --> Controller: True
deactivate DepartmentRepository
Controller --> UI: True
deactivate Controller


UI --> Administrator: OK!
deactivate UI


@enduml