@startuml
autonumber
skinparam sequenceMessageAlign center
title US08: I want to register a Student in the system

actor ASC
participant ":UI" as UI #implementation
participant "ctrl1:RegisterStudentInSystemController" as ctrl #lightyellow
participant "service1:StudentService" as service #lightblue
participant "sf1:StudentFactory" as SF #technology
participant "address1:Address" as A #physical
participant "s1:Student" as s1 #strategy
participant "sr1:StudentRepositorySpringData" as SR #lightcyan

ASC -> UI: I want to register a student in the system
activate UI
UI --> ASC: What is the Student's information?
deactivate UI
ASC -> UI: uniqueNumber, name, NIF, phone, email, \n street, postalCode, location, country
activate UI
UI -> ctrl: I want to register a Student in the system \n (uniqueNumber, name, NIF, phone, email, \n street, postalCode, location, country)
activate ctrl

ref over ctrl
    Create StudentID, name, NIF, phone, email,
    street, postalCode, location, country, academicEmail Value Objects
end ref

ctrl -> service: registerStudent (studentIDVO, nameVO, NIFVO, \n phoneVO, emailVO, streetVO, postalCodeVO, \n locationVO, countryVO, academicEmailVO)
activate service

service -> SF: createStudent (studentIDVO, nameVO, NIFVO, \n phoneVO, emailVO, streetVO, postalCodeVO, \n locationVO, countryVO, academicEmailVO)
activate SF

SF -> A**: createAddress (streetVO, postalCodeVO, \n locationVO, countryVO)
activate A

A --> SF: address1
deactivate A

SF -> s1**: new Student (studentIDVO, nameVO, NIFVO, \n phoneVO, emailVO, address1, academicEmailVO)
activate s1
s1 --> SF: s1
deactivate s1

SF -> SR: existsByStudentIDOrNIF(studentIDVO, NIFVO)
activate SR
ref over SR
    Verify duplicates
    Check if any student already exists with same StudentID or NIF
end ref
SR --> SF: False
deactivate SR
SF --> service: s1
deactivate SF

service -> SR: save(s1)
activate SR
ref over SR
    Save in Database
    Convert domain object to DataModel and persist using JPA
end ref
SR --> service: s1
deactivate SR
service --> ctrl: s1
deactivate service
ctrl --> UI: s1
deactivate ctrl
UI --> ASC: Success!
deactivate UI

@enduml