@startuml

title US13 : I want to register a Teacher and all relevant data
skinparam sequenceMessageAlign center
autonumber

actor HRC as HRC
participant UI as UI #application
participant ":US13_Controller" as controller #business
'Ref#1 : get Teacher Category's list.
'Ref#2 : get Department's list.
participant ":ITeacherService" as IteacherService #implementation
participant ":ITeacherFactory" as IteacherFactory #motivation
participant "addr:Address" as addr #physical
participant "t1:Teacher" as t #strategy
participant "t1ID:TeacherID" as tID #technology
'Ref#3 : create Teacher Career Progression tcp1.
participant ":ITeacherRepositorySpringData" as IteacherRepoJPA #skyblue
participant ":Teacher" as teacher #palegreen
participant ":TeacherMapperImpl" as tMapper #wheat
participant ":TeacherID" as teacherID #thistle
participant "tDM1:TeacherDataModel" as teacherDM #lightgray


HRC -> UI : I want to register a Teacher in the System \n Including All Relevant Data
|||
activate UI
UI --> HRC : What are the Teacher's attributes?
|||
deactivate UI
HRC -> UI : acronym, name, email, NIF, phoneNumber, academicBackground, street, postalCode, location, country
activate UI
UI -> controller : getCategoriesList()

activate controller
|||
ref over controller : \t **Interaction Use #1**  \n\n \t\t\t[[./US13_SD_Interaction_Use_#1.puml "get Teacher Category's List"]]
controller --> UI : Which Category?
deactivate controller
deactivate UI



UI -> controller : getDepartmentList()
activate UI
activate controller

|||
ref over controller : \t \t **Interaction Use #2** \n\n  \t\t\t [[./US13_SD_Interaction_Use_#2.puml "get Department's List"]]

controller --> UI : Which Department?
deactivate controller
deactivate UI



UI -> controller : registerTeacher (teacherAcronym, name, email, nif, phoneNumber, \n academicBackground, street, postalCode, location, country, departmentID)

|||
ref over controller : \t \t \t **Interaction Use #3** \n\n  \t\t\t [[./US13_SD_Interaction_Use_#3.puml "convert DTO to VO"]]
activate UI
|||
activate controller
controller -> IteacherService : registerTeacher (teacherAcronym, name, email, nif, phoneNumber, \n academicBackground, street, postalCode, location, country, departmentID)
activate IteacherService
IteacherService -> IteacherFactory : createTeacher(teacherAcronym, name, email, nif, phoneNumber, \n academicBackground, street, postalCode, location, country, departmentID)
activate IteacherFactory
IteacherFactory -> addr** : createAddress(street, postalCode, location, country)
activate addr
addr --> IteacherFactory : addr
deactivate addr

IteacherFactory -> t** : new Teacher (teacherAcronym, name, email, nif, phoneNumber, \n academicBackground, addr, departmentID)
activate t
t -> tID** : new TeacherID (teacherAcronym, NIF)
activate tID
tID --> t : t1ID
deactivate tID
t --> IteacherFactory : t1
deactivate t
IteacherFactory -> IteacherFactory : t1ID = t1.identity()
IteacherFactory -> IteacherRepoJPA : containsOfIdentity(t1ID)
activate IteacherRepoJPA
|||
loop for each Teacher in TeacherRepositorySpringDataImpl - compares IDs
    IteacherRepoJPA -> teacher : identity()
    activate teacher
    teacher -> teacherID : equals()
    activate teacherID
    teacherID --> teacher : false
    deactivate teacherID
end
    teacher --> IteacherRepoJPA : False
    deactivate teacher
IteacherRepoJPA --> IteacherFactory : false
deactivate IteacherRepoJPA


IteacherFactory --> IteacherService : t1
|||
ref over IteacherService : **Interaction Use #4** \n\n  \t\t\t\t [[./US13_SD_Interaction_Use_#4.puml "create Teacher Career Progression (tcp1)"]]


deactivate IteacherFactory
deactivate IteacherService


deactivate IteacherService
IteacherService -> IteacherRepoJPA : save(t1)
activate IteacherService
activate IteacherRepoJPA
ref over IteacherRepoJPA : \t \t **Interaction Use #5** \n \n \t \t \t \t [[./US13_SD_Interaction_Use_#5.puml "toDataModel & save || back toDomain"]]
IteacherRepoJPA --> IteacherService : teacherDomain
deactivate IteacherRepoJPA
IteacherService --> controller : true
deactivate IteacherService
controller --> UI : true
deactivate controller
UI --> HRC : Success!
deactivate UI

@enduml