@startuml
title US13 : Interaction Use #1 - Retrieve all Teacher Categories.
skinparam sequenceMessageAlign center

participant ":US13_Controller" as controller #implementation
participant ":ITeacherCategoryService" as ItcService #motivation
participant ":ITeacherCategoryRepositorySpringData" as ItcRepoJPA #physical
participant ":TeacherCategoryDataModel" as tcDataModel #application
participant ":TeacherCategoryMapperImpl" as tcMapper #strategy
participant ":ITeacherCategoryFactory" as ItcFactory #technology
participant "tc:TeacherCategory" as tc #application



activate controller
controller -> ItcService : findAll()
activate ItcService
ItcService -> ItcRepoJPA : findAll()
activate ItcRepoJPA
ItcRepoJPA -> tcDataModel : tcDataModels
activate tcDataModel
tcDataModel --> ItcRepoJPA : tcDataModel
deactivate tcDataModel
ItcRepoJPA -> tcMapper : toDomain(tcDataModel)
activate tcMapper
tcMapper -> ItcFactory : createTeacherCategory(name)
activate ItcFactory
ItcFactory -> tc** : new Teacher Category (name)
activate tc
tc --> ItcFactory : tc[i]
deactivate tc
ItcFactory --> tcMapper : tc[i]
deactivate ItcFactory
tcMapper --> ItcRepoJPA : tc[i]
deactivate tcMapper
ItcRepoJPA -> ItcRepoJPA : save(tc[i])
ItcRepoJPA --> ItcService : tcList
deactivate ItcRepoJPA
ItcService --> controller : tcList
@enduml