@startuml
title US13 : Interaction Use #4 - Create TeacherCareerProgression
skinparam sequenceMessageAlign center

participant ":ITeacherService" as IteacherService #technology
participant ":ITeacherCareerProgressionRepositorySpringData" as ItcpRepositoryJPA #physical
participant ":TeacherCareerProgressionMapperImpl" as tcpMapper #strategy
participant ":ITeacherCareerProgressionFactory" as tcpFactory #technology
participant ":TeacherCareerProgression" as careerProgression
participant "tcp1:TeacherCareerProgression" as TCP #application
participant "tc1:TeacherCategory1" as tc1 #business


IteacherService -> ItcpRepositoryJPA : createTeacherCareerProgression \n (tID1, tc, workingPercentage, date)
activate IteacherService
activate ItcpRepositoryJPA
ItcpRepositoryJPA -> tcpFactory : createTeacherCareerProgression \n (tID1, tcID, workingPercentage, date)
activate tcpFactory
tcpFactory -> TCP** : new TeacherCareerProgression \n (tID1, tcID, workingPercentage, date)
activate TCP
TCP --> tc1** : new Teacher Category \n (tcID, name)
activate tc1
tc1 --> TCP : tc
deactivate tc1
TCP --> tcpFactory : tcp1
deactivate TCP
tcpFactory --> ItcpRepositoryJPA : tcp1
deactivate tcpFactory
ItcpRepositoryJPA -> ItcpRepositoryJPA : isTeacherCareerProgressionDuplicate(tcp1)
ItcpRepositoryJPA -> careerProgression : sameAs(tcp1)
activate careerProgression
careerProgression --> ItcpRepositoryJPA : false
deactivate careerProgression
ItcpRepositoryJPA -> ItcpRepositoryJPA : save(tcp1)
ItcpRepositoryJPA --> IteacherService : true
@enduml