@startuml
skinparam linetype polyline
left to right direction
hide empty methods
hide empty members
title "Domain Diagram"

' Entities
entity Facility {
}

entity "School Year" {
  startYear
  endYear
}

entity Department {
  name
  acronym
}

entity Course {
  name
  acronym
  qtyECTS
}

entity Address {
  postalCode
  street
  city
  country
}

entity "Teacher Category" {
  categoryName
}

entity Teacher {
  name
  acronym
  NIF
  email
  phoneNumber
}

entity Programme {
  name
  acronym
  qtyECTS
  qtySemesters
}

entity Enrolment {
}

entity Student {
  uniqueNumber
  name
  NIF
  phoneNumber
  email
}

entity "Degree Type" {
  name
  maxECTS
}

entity "Access Method" {
  name
}

Facility "1..*" -up- "1" Department : Aggregates <
Department "1" --- "1   " Teacher : Department Director oversees <
Department "1" --- "*" Teacher : Aggregates >
Course "*" -- "*" Teacher : Teaches <
Address "1" -right- "1" Student : Has <
Teacher "1" -- "1" Address : Has >
"Teacher" "*" -- "1" "Teacher Category" : Has >
Programme "1" -- "1..*" Course : Belongs to <
Programme "1" -- "*" Enrolment : Has >
Programme "*" -right- "1" Department : Assigned to >
Programme "1..*" -- "1  " Teacher : Programme Director oversees <
Programme "*" -- "1" "Degree Type" : Has >
Student "1" -- "1..*" Enrolment : Enrols >
Enrolment "1..*" -- "1" "Access Method" : Has >
@enduml