@startuml
skinparam ranksep 120
skinparam nodesep 120
skinparam classArrowFontSize 16

package "CourseInStudyPlan Aggregate" {
    entity "<<root>>\nCourseInStudyPlan" {
    }
}

package "StudyPlan Aggregate" {
    entity "<<root>>\nStudyPlan" {
    }
}

package "DegreeType Aggregate" {
    entity "<<root>>\nDegreeType" {
    }
}

package "Programme Aggregate" {
    entity "<<root>>\nProgramme" {
    }
}

package "Course Aggregate" {
    entity "<<root>>\nCourse" {
    }
}

package "SchoolYear Aggregate" {
    entity "<<root>>\nSchoolYear" {
    }
}

package "ProgrammeEdition Aggregate" {
    entity "<<root>>\nProgrammeEdition" {
    }
}

package "CourseEdition Aggregate" {
    entity "<<root>>\nCourseEdition" {
    }
}

package "CourseEditionEnrolment Aggregate" {
    entity "<<root>>\nCourseEditionEnrolment" {
    }
}

package "ProgrammeEditionEnrolment Aggregate" {
    entity "<<root>>\nProgrammeEditionEnrolment" {
    }
}

package "ProgrammeEnrolment Aggregate" {
    entity "<<root>>\nProgrammeEnrolment" {
    }
}

package "AccessMethod Aggregate" {
    entity "<<root>>\nAccessMethod" {
    }
}

package "Student Aggregate" {
    entity "<<root>>\nStudent" {
    }
}

package "StudentGrade Aggregate" {
    entity "<<root>>\nStudentGrade" {
    }
}

package "Teacher Aggregate" {
    entity "<<root>>\nTeacher" {
    }
}

package "TeacherCareerProgression Aggregate" {
    entity "<<root>>\nTeacherCareerProgression" {
    }
}

package "TeacherCategory Aggregate" {
    entity "<<root>>\nTeacherCategory" {
    }
}

package "Department Aggregate" {
    entity "<<root>>\nDepartment" {
    }
}

"<<root>>\nStudyPlan" "*" <-r- "1" "<<root>>\nCourseInStudyPlan"
"<<root>>\nStudyPlan" "1" --> "*" "<<root>>\nProgramme"
"<<root>>\nProgramme" "1" <-- "*" "<<root>>\nProgrammeEdition"
"<<root>>\nProgrammeEdition" "1" <-- "*" "<<root>>\nCourseEdition"
"<<root>>\nCourseInStudyPlan" "1" <-- "*" "<<root>>\nCourseEdition"
"<<root>>\nCourseEdition" "1" <-- "*" "<<root>>\nCourseEditionEnrolment"
"<<root>>\nCourseEdition" "1" <-- "*" "<<root>>\nStudentGrade"
"<<root>>\nCourseEditionEnrolment" "*" -u-> "1" "<<root>>\nStudent"
"<<root>>\nStudent" "1" <-- "*" "<<root>>\nProgrammeEnrolment"
"<<root>>\nProgrammeEnrolment" "1..*" --> "1" "<<root>>\nAccessMethod"
"<<root>>\nProgrammeEditionEnrolment" "*" -u-> "1" "<<root>>\nStudent"
"<<root>>\nProgrammeEditionEnrolment" "*" --> "1" "<<root>>\nProgrammeEdition"
"<<root>>\nSchoolYear" "1" <-d- "*" "<<root>>\nProgrammeEdition"
"<<root>>\nDegreeType" "1" <-d- "*" "<<root>>\nProgramme"
"<<root>>\nTeacher" "0..1" <-d- "*" "<<root>>\nCourseEdition"
"<<root>>\nTeacher" "1" <-d- "*" "<<root>>\nProgramme"
"<<root>>\nTeacherCategory" "1" <-u- "*" "<<root>>\nTeacherCareerProgression"
"<<root>>\nTeacher" "1" <-r- "1..*" "<<root>>\nTeacherCareerProgression"
"<<root>>\nTeacher" "1" -l-> "1" "<<root>>\nDepartment"
"<<root>>\nStudent" "1" <-- "*" "<<root>>\nStudentGrade"
"<<root>>\nCourse" "1" <-d- "*" "<<root>>\nCourseInStudyPlan"
"<<root>>\nProgrammeEnrolment" "*" --> "1" "<<root>>\nProgramme"
"<<root>>\nProgramme" "*" --> "1" "<<root>>\nDepartment"

@enduml