@startuml
actor ASC as Admin
participant ":System" as System
autonumber

Admin -> System  : I Want to register a Programme in the System.

System --> Admin : Choose a Degree Type, a Department and a Teacher?

Admin -> System  : Degree Type, Department and Programme Director chosen.

System --> Admin  : Name? Acronym? quantityOfEcts? quantityOfSemesters?

Admin -> System  : Name. Acronym. quantityOfEcts. quantityOfSemesters.

System --> Admin  : Done!

@enduml