@startuml
autonumber

title US27: As an ASC, I want to register a programme in the system.

actor ASC as Admin

participant ":UI" as UI #lightblue
participant ":ControllerUS27" as C #lightblue
participant ":ProgrammeRepository" as PR #lightblue

participant "ProgrammeFactory" as PF #lightblue





Admin -> UI ++ #application : I want to register a Programme in the System,\n including a Study Plan.

UI --> Admin -- : What are the attributes?

Admin -> UI ++ #application : name, acronym, quantityOfEcts, quantityOfSemesters, degreeType, \n department, programmeDirector

UI -> C ++ #application : registerAProgrammeDDDInTheSystem(name, acronym, quantityOfEcts, \nquantityOfSemesters, degreeTypeID, department, programmeDirectorID)

C -> PR ++ #application : registerProgramme(name, acronym, quantityOfEcts, quantityOfSemesters, \ndegreeTypeID, departmentID, programmeDirectorID)


PR -> PF ++ #application : registerProgramme (name, acronym, quantityOfEcts, quantityOfSemesters, \ndegreeTypeID, departmentID, programmeDirectorID)

create "P1:Programme" as P #lightblue

PF -> P ++ #application : registerProgramme (name, acronym, quantityOfEcts, quantityOfSemesters, \ndegreeTypeID, departmentID, programmeDirectorID)

P -> P : Validations


P --> PF -- : Programme P1
PF --> PR -- : Programme P1
participant ":List<Programme>" as PL
PR -> PL ++ #application : contains(P1)
PL --> PR : False
PR -> PL : add(P1)
PL --> PR --: True

PR --> C -- : True
C --> UI -- : True


UI --> Admin -- : Done!


@enduml