@startuml
skinparam linetype ortho

title US11:  I want to register a programme in the system

class US11_RegisterAProgrammeInTheSystem {
   }

    class DegreeTypeID <<ValueObject>> {
    }

package "Programme Aggregate" {
    entity "<<root>>\nProgramme" {
    }
}

class TeacherID <<ValueObject>> {
}


entity DepartmentID <<ValueObject>> {
}


US11_RegisterAProgrammeInTheSystem ....> "<<root>>\nProgramme"


DegreeTypeID "1" <-right- "*" "<<root>>\nProgramme"
TeacherID "1" <-right- "*" "<<root>>\nProgramme"

DepartmentID "1" <-up- "*" "<<root>>\nProgramme"

@enduml