@startuml
actor ASC as Admin
participant ":System" as System
autonumber

Admin -> System  : I Want to register a Programme in the System.
System --> Admin  : Name? Acronym? quantityOfEcts? quantityOfSemesters?  \nDegreeType? Department? Programme Director?
Admin -> System  : Name! Acronym! quantityOfEcts! quantityOfSemesters!  \nDegreeType! Department! Programme Director!
System --> Admin  : Done!

@enduml