@startuml
actor ASC as Admin
participant ":System" as System

Admin -> System  : I Want to register a Programme in the System.
System --> Admin  : Name? Acronym? quantityOfEcts? quantityOfSemesters?  DegreeType? Department? Programme Director?
Admin -> System  : Name! Acronym! quantityOfEcts! quantityOfSemesters!  DegreeType! Department! Programme Director!
System --> Admin  : Sure?
Admin -> System  : Yes!
System --> Admin  : Done!

@enduml