@startuml
!pragma layout smetana

class US16_EnrolAStudentInACourseEditionController {
    +US16_EnrolAStudentInACourseEditionController(ceeRepository: CourseEditionEnrolmentRepository,
    peeRepository: ProgrammeEditionEnrolmentRepository , courseEditionRepository: CourseEditionRepository)
    +enrolStudentInCourseEdition(student: Student, courseEdition: CourseEdition): boolean
    +findProgrammeEditionsThatStudentIsEnrolled(student: Student): List<ProgrammeEdition>
    +findCourseEditionsByProgrammeEdition(programmeEdition: ProgrammeEdition): List<CourseEdition>
}

class CourseEditionEnrolmentFactoryImpl{
    +createCourseEditionEnrolment(student: Student, courseEdition: CourseEdition)
}

class CourseEditionEnrolment {
    -_enrolmentDate: LocalDate
    - _isActive: boolean
    +CourseEditionEnrolment(student:Student, courseEdition: CourseEdition)
    +equals (obj: Object): boolean
}

interface ICourseEditionEnrolmentListFactory{
    +getCourseEditionEnrolmentList(): Set<CourseEditionEnrolment>
}

class CourseEditionEnrolmentListFactoryImpl {
    +getCourseEditionEnrolmentList(): Set<CourseEditionEnrolment>
}

interface ICourseEditionEnrolmentFactory{
    +createCourseEditionEnrolment(student: Student, courseEdition: CourseEdition): CourseEditionEnrolment
}

class CourseEditionEnrolmentRepository {
    +CourseEditionEnrolmentRepository (courseEditionEnrolmentFactory: ICourseEditionEnrolmentFactory, courseEditionEnrolmentListFactory: ICourseEditionEnrolmentListFactory)
    +enrolStudentInACourseEdition (student: Student, courseEdition: CourseEdition): boolean
}

class ProgrammeEditionEnrolment {
    -_enrolmentDate: LocalDate
    +ProgrammeEditionEnrolment(student:Student, programmeEdition: ProgrammeEdition)
    +findStudentInProgrammeEditionEnrolment () : Student
    +findProgrammeEditionInEnrolment () : ProgrammeEdition
}

interface CourseEditionEnrolmentSet {
    +add(courseEditionEnrolment: CourseEditionEnrolment): boolean
}

class ProgrammeEditionEnrolmentRepository {
    +ProgrammeEditionEnrolmentRepository (programmeEditionEnrolmentFactory: ProgrammeEditionEnrolmentFactory)
    +findProgrammeEditionsThatStudentIsEnrolled(student: Student): List<ProgrammeEdition>
}

class Student {
    -_uniqueNumber:String
    -_name:String
    -_NIF:String
    -_phone:String
    -_email:String
    -_institutionalEmail:Sring
    +Student(uniqueNumber: String, name: String, NIF: String, phone: String, email: String, address: Address)
}

class Address {
     -_street:String
     -_postalCode: String
     -_location: String
     -_country: String
     +Address(street: String, postalCode: String, location: String, country: String)
}

class CourseEdition {
    +CourseEdition(programmeEdition: ProgrammeEdition, course: Course)
    +whatProgrammeEditionBelongsThisCourseEdition () : ProgrammeEdition
}

class CourseEditionRepository {
    +CourseEditionRepository(courseEditionFactory: CourseEditionFactory)
    +findCourseEditionsByProgrammeEdition(programmeEdition: ProgrammeEdition) : List<ProgrammeEdition>
}

CourseEdition "_listOfCE * " <-u- "1   " CourseEditionRepository
Student "  _student  1 " <-u- " * " CourseEditionEnrolment
CourseEditionEnrolment "    *  " --> "    _cE  1            " CourseEdition
ProgrammeEditionEnrolment "      *  " -u-> "_student 1    " Student
ProgrammeEditionEnrolment " *    " <-- "1   " ProgrammeEditionEnrolmentRepository
US16_EnrolAStudentInACourseEditionController "1   "..> "1    " CourseEditionRepository
US16_EnrolAStudentInACourseEditionController "1  "..> "1       " ProgrammeEditionEnrolmentRepository
US16_EnrolAStudentInACourseEditionController "1   "..> "  1    " CourseEditionEnrolmentRepository
Address "1 _address            " <-u- "  1  " Student
CourseEditionEnrolmentSet "   1            " -u->  "_setOfCee *    " CourseEditionEnrolment
CourseEditionEnrolmentRepository " 1  " -u-> "_setOfCee  1       " CourseEditionEnrolmentSet
CourseEditionEnrolmentRepository"   1  " ..> " *   "CourseEditionEnrolment
ICourseEditionEnrolmentFactory <|.. CourseEditionEnrolmentFactoryImpl
ICourseEditionEnrolmentListFactory <|.. CourseEditionEnrolmentListFactoryImpl
CourseEditionEnrolmentRepository "1  " .u.> "1  " ICourseEditionEnrolmentListFactory
CourseEditionEnrolmentRepository "1  " ..> "_ceeFactory  1      " ICourseEditionEnrolmentFactory
ICourseEditionEnrolmentFactory "1  " ..> "1  " CourseEditionEnrolment
ICourseEditionEnrolmentListFactory "1  " .u.> "1  " CourseEditionEnrolmentSet

@enduml